#!/sbin/openrc-run

name="log2ram"
description="log2ram init.d file for Alpine Linux"

command="/usr/bin/log2ram"
extra_started_commands="write"

depend() {
	after localmount
    before logger
}

start() {
    ebegin "Starting Log2Ram"
        $command start
    eend $?
}

stop() {
    ebegin "Stopping Log2Ram"
        $command stop
    eend $?
}

write() {
    ebegin "Syncing logs to disk"
        $command write
    eend $?
}
